# Generated by Django 2.2.3 on 2019-07-23 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1)])),
                ('frowns', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1)])),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aminer_id', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.IntegerField(null=True)),
                ('abstract', models.TextField(max_length=10000, null=True)),
                ('n_citation', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('1', 'Early Development'), ('2', 'Writing and Editing'), ('3', 'Ready for Submission'), ('4', 'Submitted'), ('5', 'Revising'), ('6', 'In Print')], max_length=100, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='format (mm/dd/yyyy)', null=True)),
                ('event', models.CharField(choices=[('1', 'Working Paper'), ('2', 'Presentation'), ('3', 'Submitted'), ('4', 'Rejected'), ('5', 'Revise and Resubmitted'), ('6', 'Accepted'), ('7', 'Appeared in Journal')], max_length=50, null=True)),
                ('comment', models.TextField()),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('likes', models.IntegerField(default=0)),
                ('frowns', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20)])),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
    ]
