# Generated by Django 2.2 on 2019-05-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190505_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='aminer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
