# Generated by Django 2.2 on 2019-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20190514_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='recommend',
        ),
        migrations.AddField(
            model_name='paper',
            name='recommend',
            field=models.ManyToManyField(null=True, related_name='_paper_recommend_+', to='search.Paper'),
        ),
    ]
