# Generated by Django 2.2 on 2019-05-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
